# Change these first
owner: codustry # Your GitHub username
repo: gebwai_status # Your GitHub repository name

# Add your sites here
sites:
  - name: gebwai.com
    url: https://gebwai.com
  - name: liff
    url: $LIFF_SITE
  - name: server
    url: $API_ENDPOINT
  - name: LINE API
    url: https://api.line.me/v2/bot/channel/webhook/endpoint
    headers:
      - "Authorization: Bearer $LINE_ACCESS_TOKEN"
      - "Content-Type:application/json"

assignees: # Users to assign downtime issues (optional)
  - wasdee

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.gebwai.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://ik.imagekit.io/tqbc8pye197/webapp/favicon.png
  name: Gebwai Status
  introTitle: "**Gebwai** is a LINE chatbot to make you work on line more productive."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/codustry/gebwai_status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
